"""Tunable matching configuration.

Holds the editable knobs that drive scoring and filtering: desired roles and
their weights, skill keywords, title include/exclude lists, pinned companies,
and the city aliases used by the location boost.
"""

TARGET_ROLES: list[str] = [
    "backend engineer",
    "backend developer",
    "software engineer",
    "software developer",
    "platform engineer",
    "infrastructure engineer",
    "ml engineer",
    "machine learning engineer",
    "ai engineer",
    "ai infrastructure",
    "distributed systems engineer",
    "python engineer",
    "site reliability engineer",
    "devops engineer",
    "data engineer",
    "full stack engineer",
    "full-stack engineer",
    "fullstack engineer",
    "full stack developer",
]

ROLE_WEIGHTS: dict[str, int] = {
    "software engineer": 58,
    "python engineer": 55,
    "backend engineer": 54,
    "ai engineer": 53,
    "ml engineer": 52,
    "machine learning engineer": 52,
    "ai infrastructure": 52,
    "backend developer": 50,
    "software developer": 50,
    "platform engineer": 48,
    "infrastructure engineer": 48,
    "distributed systems engineer": 48,
    "site reliability engineer": 45,
    "full stack engineer": 42,
    "full-stack engineer": 42,
    "fullstack engineer": 42,
    "full stack developer": 40,
    "devops engineer": 40,
    "data engineer": 38,
}

MUST_HAVE_KEYWORDS: list[str] = [
    "python",
    "backend",
    "distributed systems",
    "microservices",
    "redis",
    "kubernetes",
    "docker",
    "asyncio",
    "inference",
    "api",
    "postgres",
    "postgresql",
    "kafka",
    "grpc",
    "scalability",
]

NICE_TO_HAVE_KEYWORDS: list[str] = [
    "go",
    "golang",
    "rust",
    "fastapi",
    "django",
    "flask",
    "aws",
    "gcp",
    "terraform",
    "ci/cd",
    "graphql",
    "elasticsearch",
    "pytorch",
    "llm",
    "rag",
    "vector database",
    "observability",
]

EXCLUDE_KEYWORDS: list[str] = [
    "qa",
    "manual testing",
    "sales",
    "account executive",
    "marketing",
    "recruiter",
    "customer success",
    "support engineer",
    "frontend only",
]

PINNED_COMPANIES: list[str] = [
    "Zscaler",
]

TITLE_INCLUDE_KEYWORDS: list[str] = [
    "software",
    "engineer",
    "developer",
    "programmer",
    "architect",
    "sde",
    "swe",
    "backend",
    "back end",
    "back-end",
    "full stack",
    "fullstack",
    "full-stack",
    "infrastructure",
    "infra",
    "platform",
    "devops",
    "sre",
    "site reliability",
    "python",
    "ai",
    "ml",
    "machine learning",
    "deep learning",
    "llm",
    "genai",
    "gen ai",
    "mlops",
    "inference",
    "data engineer",
]

TITLE_EXCLUDE_KEYWORDS: list[str] = [
    "team lead",
    "tech lead",
    "team leader",
    "tech leader",
    "manager",
    "director",
    "sales",
    "presales",
    "pre-sales",
    "solution engineer",
    "solutions engineer",
    "account executive",
    "account manager",
    "marketing",
    "recruiter",
    "talent acquisition",
    "human resources",
    "finance",
    "accountant",
    "legal",
    "customer success",
    "customer support",
    "technical support",
    "mechanical",
    "electrical",
    "electronics",
    "hardware",
    "analog",
    "rf engineer",
    "vlsi",
    "asic",
    "physical design",
    "civil engineer",
    "industrial engineer",
    "chemical",
    "technician",
    "field application",
    "designer",
    "ui/ux",
    "ux/ui",
]

REMOTE_TERMS: list[str] = ["remote", "anywhere", "work from home", "wfh", "distributed"]

ISRAEL_LOCATION_TERMS: list[str] = [
    "israel",
    "ישראל",
    "tel aviv",
    "tel-aviv",
    "telaviv",
    "tlv",
    "herzliya",
    "herzilya",
    "haifa",
    "raanana",
    "ra'anana",
    "jerusalem",
    "petah tikva",
    "petach tikva",
    "petah-tikva",
    "netanya",
    "beer sheva",
    "be'er sheva",
    "beersheba",
    "rehovot",
    "yokneam",
    "yoqneam",
    "kfar saba",
    "ramat gan",
    "caesarea",
    "hod hasharon",
    "or yehuda",
    "airport city",
    "modiin",
    "modi'in",
    "lod",
    "ness ziona",
    "givatayim",
    "holon",
    "bnei brak",
    "תל אביב",
    "חיפה",
    "ירושלים",
    "הרצליה",
    "רעננה",
    "רמת גן",
    "פתח תקווה",
    "נתניה",
    "ראש העין",
    "באר שבע",
    "רחובות",
    "יקנעם",
    "כפר סבא",
    "הוד השרון",
    "מודיעין",
    "נס ציונה",
    "גבעתיים",
    "חולון",
    "בני ברק",
    "לוד",
    "אור יהודה",
    "קיסריה",
    "פתח תקוה",
    "עומר",
]

CITY_ALIASES: dict[str, list[str]] = {
    "tel aviv": ["tel aviv", "tel-aviv", "telaviv", "tlv", "תל אביב"],
    "herzliya": ["herzliya", "herzilya", "הרצליה"],
    "haifa": ["haifa", "חיפה"],
    "jerusalem": ["jerusalem", "ירושלים"],
    "raanana": ["raanana", "ra'anana", "רעננה"],
    "petah tikva": ["petah tikva", "petach tikva", "petah-tikva", "פתח תקווה", "פתח תקוה"],
    "netanya": ["netanya", "נתניה"],
    "ramat gan": ["ramat gan", "רמת גן"],
    "beer sheva": ["beer sheva", "be'er sheva", "beersheba", "באר שבע"],
    "rehovot": ["rehovot", "רחובות"],
    "yokneam": ["yokneam", "yoqneam", "יקנעם"],
    "kfar saba": ["kfar saba", "כפר סבא"],
    "caesarea": ["caesarea", "קיסריה"],
    "hod hasharon": ["hod hasharon", "הוד השרון"],
    "or yehuda": ["or yehuda", "אור יהודה"],
    "airport city": ["airport city"],
    "modiin": ["modiin", "modi'in", "מודיעין"],
    "lod": ["lod", "לוד"],
    "ness ziona": ["ness ziona", "נס ציונה"],
    "givatayim": ["givatayim", "גבעתיים"],
    "holon": ["holon", "חולון"],
    "bnei brak": ["bnei brak", "בני ברק"],
    "rosh haayin": ["rosh haayin", "ראש העין"],
    "omer": ["omer", "עומר"],
}

USER_YEARS_EXPERIENCE: int = 5

OVERQUALIFIED_TITLE_TERMS: list[str] = [
    "principal",
    "staff",
    "distinguished",
    "director",
    "head of",
    "vp",
    "vice president",
    "chief",
    "fellow",
]

SENIORITY_TERMS: dict[str, list[str]] = {
    "principal": ["principal", "staff", "distinguished"],
    "senior": ["senior", "sr.", "lead", "team lead", "tech lead"],
    "mid": ["mid-level", "intermediate"],
    "junior": ["junior", "jr.", "entry level", "intern"],
}
